#!/bin/bash
SYNC="/usr/local/bin/syncoid --quiet"
delete_snaps() {
  zfs list -r -t snapshot -Ho name "$1" | grep "$2" | xargs -rn 1 zfs destroy
}
# Replicate rpool -> tank
$SYNC rpool/ROOT/ubuntu tank/ubuntu
$SYNC rpool/home tank/home
$SYNC -r rpool/vmware tank/vmware

# Cleanup unneeded snapshots
delete_snaps tank @backup_

# Replicate tank -> backup
$SYNC tank/duplicity backup/tank/duplicity
$SYNC --no-sync-snap -r tank backup/tank

