#!/bin/bash
set -o pipefail
DEST=/backup/dump
BACKUP="tank/backup ssd/home ssd/vmware/Windows10"

# Lock to prevent simultaneous runs
TMP=/var/lock/zfs-backup.lock
exec 99>>$TMP
flock -n 99 || exit 1
trap "rm -f $TMP" EXIT

# Determine backup level by schedule
get_level () {
    fsname=$1
    touch -d '-1 month' $TMP
    [ $fsname.0.gz_00 -ot $TMP ] && return 0
    touch -d '-1 week' $TMP
    [ $fsname.1.gz_00 -ot $TMP ] && return 1
    touch -d '-1 day' $TMP
    [ $fsname.2.gz_00 -ot $TMP ] && return 2
    return 3
}

cd $DEST
for fs in $BACKUP
do
    fsname=${fs//\//_}
    get_level $fsname
    level=$?
    rm -f $fsname.[$level-9].gz_*
    zfs-dump -$level $fs | pigz | split -d -b 5G - $fsname.$level.gz_
    [ $? -ne 0 ] && exit 1
done

# Sync to cloud outside business hours
hour=$(date +%H)
[ $hour -ge 7 -a $hour -le 18 ] && exit
rclone sync $DEST onedrive:backups
