#!/bin/bash
set -o pipefail
DEST=/backup/dump
BACKUP="rpool/ROOT/ubuntu rpool/home rpool/vmware/Windows10"
GPG="gpg -e -r lonnie"

# Lock to prevent simultaneous runs
LOCK=/var/lock/zfs-backup.lock
exec 99>>$LOCK
flock -n 99 || exit 1
trap "rm -f $LOCK" EXIT

# Determine backup level by schedule
get_level () {
    fsname=$1
    touch -d '-1 month' $TMP
    [ $fsname.0.gz.gpg -ot $TMP ] && return 0
    touch -d '-1 week' $TMP
    [ $fsname.1.gz.gpg -ot $TMP ] && return 1
    touch -d '-23 hours' $TMP
    [ $fsname.2.gz.gpg -ot $TMP ] && return 2
    return 3
}

cd $DEST || exit 1
for fs in $BACKUP
do
    fsname=${fs//\//_}
    get_level $fsname
    level=$?
    TMP=$(mktemp -p .)
    zfs-dump -$level $fs | pigz | $GPG > $TMP
    if [ $? -ne 0 ]; then
        rm $TMP
        exit 1
    fi
    rm -f $fsname.[$level-9].gz.gpg
    mv $TMP $fsname.$level.gz.gpg
done

# Sync to cloud outside business hours
hour=$(date +%H)
[ $hour -ge 7 -a $hour -le 18 ] && bwlimit="--bwlimit 2000"
rclone $bwlimit sync $DEST drive:backup/fungus

